apiDir: ../headless-forum-subscriptions-api/src/main/java
apiPackagePath: com.liferay.headless.forum.subscriptions
application:
    baseURI: /forum-subscriptions
    className: ForumSubscriptionsApplication
    name: Liferay.Forum.Subscriptions
author: Neil Griffin
clientDir: ../headless-forum-subscriptions-client/src/main/java
compatibilityVersion: 6
forcePredictableOperationId: true
oauth2ScopeExtender: true
testDir: ../headless-forum-subscriptions-test/src/testIntegration/java
