#
# MySQL
#
#jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
#jdbc.default.url=jdbc:mysql://localhost/lportal
#jdbc.default.username=root
#jdbc.default.password=

#
# REST API — enable Basic Auth for local development
#
auth.verifier.BasicAuthHeaderAuthVerifier.urls.includes=*